Dev. checkpoint.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -17,6 +17,18 @@ export LOG_PREFIX="$BUILD_DIR/tmp"
 mkdir -p "$LOG_PREFIX"
 touch "$LOG_PREFIX/nginx.pid"
 
+CURRENT_VER="$(("$COMPILED_NGINX"/progs/nginx/sbin/nginx -v 2>&1 | cut -d'/' -f2) || :)"
+LATEST_VER="$((git ls-remote -t https://github.com/openresty/openresty | cut -d'/' -f 3 | sort -r | grep -P '^v[0-9\.]+$' | head -n 1 | cut -d'v' -f2) || :)"
+
+if [[ -z "$LATEST_VER" ]]; then
+  echo "-----> !!! Latest version not found." >&2
+else
+  echo "-----> Latest OpenResty: $LATEST_VER"
+  if [[ "$CURRENT_VER" != "$LATEST_VER" ]]; then
+    rm -r "$COMPILED_NGINX"
+  fi
+fi
+
 echo "-----> PATH: $PATH"
 echo "-----> BUILD_DIR: $BUILD_DIR"
 echo "-----> CACHE_DIR: $CACHE_DIR"
@@ -24,7 +36,7 @@ echo "-----> ENV_DIR:   $ENV_DIR"
 echo "-----> PREFIX:    $PREFIX"
 echo "-----> LOG_PREFIX:$LOG_PREFIX"
 
-if [[ -d "$COMPILED_NGINX/progs/nginx" ]] ; then
+if [[ ! -z "$("$COMPILED_NGINX"/progs/nginx/sbin/nginx -v || :)" ]] ; then
   echo "=====> ls $COMPILED_NGINX"
   ls -al "$COMPILED_NGINX/progs"
 
@@ -55,18 +67,6 @@ echo "-----> Installing OpenResty:"
 #           and on:
 #           https://github.com/geoffleyland/heroku-buildpack-openresty/blob/master/bin/compile
 
-CURRENT_VER="$(("$PREFIX"/nginx/sbin/nginx -v 2>&1 | cut -d'/' -f2) || :)"
-LATEST_VER="$((git ls-remote -t https://github.com/openresty/openresty | cut -d'/' -f 3 | sort -r | grep -P '^v[0-9\.]+$' | head -n 1 | cut -d'v' -f2) || :)"
-
-
-if [[ -z "$LATEST_VER" ]]; then
-  echo "-----> !!! Latest version not found." >&2
-  exit 1
-fi
-if [[ "$CURRENT_VER" == "$LATEST_VER" ]]; then
-  echo "-----> Already installed: $CURRENT_VER in $PREFIX" >&2
-  exit 0
-fi
 
 cd "$PREFIX"
 
