Refactoring. And fixes.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,22 +1,91 @@
 #!/usr/bin/env bash
 #
 #
-THE_ARGS="$@"
-THIS_DIR="$(dirname "$(dirname "$0")")"
+set -u -e -o pipefail
 
 BUILD_DIR="$1"; shift
 CACHE_DIR="$1"; shift
 ENV_DIR="$1"; shift
 
-set -u -e -o pipefail
+export PREFIX="$HOME/progs"
+mkdir -p "$PREFIX"
 
-cd "$CACHE_DIR"
-
-cd "$BUILD_DIR"
-mkdir -p progs
-mkdir -p tmp
+LOG_PREFIX="$HOME/tmp"
+mkdir -p "$LOG_PREFIX"
 
 echo "-----> PATH: $PATH"
-echo "-----> Installing OpenResty: "
-source "$THIS_DIR/install.openresty.sh"
-upgrade-openresty
+echo "-----> BUILD_DIR: $BUILD_DIR"
+echo "-----> CACHE_DIR: $CACHE_DIR"
+echo "-----> ENV_DIR:   $ENV_DIR"
+echo "-----> PREFIX:    $PREFIX"
+echo "-----> LOG_PREFIX:$LOG_PREFIX"
+echo "----->"
+echo "-----> Installing OpenResty:"
+
+# Based on: lua_setup install openresty
+#           and on:
+#           https://github.com/geoffleyland/heroku-buildpack-openresty/blob/master/bin/compile
+
+CURRENT_VER="$(("$PREFIX"/nginx/sbin/nginx -v 2>&1 | cut -d'/' -f2) || :)"
+LATEST_VER="$(git ls-remote -t https://github.com/openresty/openresty | cut -d'/' -f 3 | sort -r | grep -P '^v[0-9\.]+$' | head -n 1 | cut -d'v' -f2)"
+
+if [[ -z "$LATEST_VER" ]]; then
+  echo "-----> !!! Latest version not found." >&2
+  exit 1
+fi
+
+if [[ "$CURRENT_VER" == "$LATEST_VER" ]]; then
+  echo "-----> Already installed: $CURRENT_VER in $PREFIX" >&2
+  exit 0
+fi
+
+cd "$PREFIX"
+
+local +x ARCHIVE="openresty-${LATEST_VER}.tar.gz"
+local +x SOURCE_DIR=$(basename "$ARCHIVE" ".tar.gz")
+echo "-----> Downloading $ARCHIVE... "
+echo "-----> in directory: $PWD ["
+ls -1
+echo "-----> ]"
+
+if [[ ! -d "$SOURCE_DIR" ]]; then
+  if [[ ! -s $ARCHIVE ]]; then
+    wget --quiet "https://openresty.org/download/${ARCHIVE}"
+  fi
+  tar -xvf ${ARCHIVE} >/dev/null || { rm $ARCHIVE; rm -rf "$SOURCE_DIR"; exit 1; }
+fi
+
+cd $SOURCE_DIR
+echo "-----> in openresty source directory: $PWD"
+
+local +x PROCS="$(grep -c '^processor' /proc/cpuinfo)"
+
+# NOTE: /sbin in PATH is needed because OpenResty
+# compilation requires ldconfig in PATH.
+PATH="$PATH:/sbin" ./configure                      \
+  --prefix="$PREFIX"             \
+  --with-http_iconv_module       \
+  --without-http_redis2_module   \
+  --with-pcre-jit                \
+  --with-ipv6                    \
+  --with-http_ssl_module         \
+  --error-log-path="$LOG_PREFIX/startup.error.log" \
+  --http-log-path="$LOG_PREFIX/startup.access.log"  \
+  -j$(($PROCS - 1))
+
+make
+make install
+
+set "-x"
+ln -s "$PREFIX"/luajit/lib/libluajit-*.so.2*       "$PREFIX"/luajit/lib/
+ln -s "$PREFIX"/luajit/bin/luajit-*                "$PREFIX"/bin/
+ln -s "$PREFIX"/luajit/include/luajit-*            "$PREFIX"/include/
+ln -s "$PREFIX"/nginx/sbin/nginx                   "$PREFIX"/bin/nginx
+set +x
+
+echo -n "-----> Installed: "
+"$PREFIX"/nginx/sbin/nginx -v || {
+  rm -rf "$PREFIX"
+  exit 1;
+}
+
